module.exports = {
  '/company/jobs': 'https://www.npmjs.com/jobs',
  '/company/about': 'https://www.npmjs.com/about',
  '/company/npm-weekly': 'https://www.npmjs.com/npm-weekly',
  '/company/weekly': 'https://www.npmjs.com/npm-weekly',
  '/company/private-npm': 'https://www.npmjs.com/features',
  '/company/private-packages': 'https://www.npmjs.com/features',
  '/company/policies': 'https://www.npmjs.com/policies',
  '/company/security': 'https://www.npmjs.com/policies/security',




  '/policies': 'https://www.npmjs.com/policies',
  '/policies/conduct': 'https://www.npmjs.com/policies/conduct',
  '/policies/domains': 'https://www.npmjs.com/policies/domains',
  '/policies/organization-plan': 'https://www.npmjs.com/policies/organization-plan',
  '/policies/terms': 'https://www.npmjs.com/policies/terms',
  '/policies/crawlers': 'https://www.npmjs.com/policies/crawlers',
  '/policies/enterprise-terms': 'https://www.npmjs.com/policies/enterprise-terms',
  '/policies/personal-plan': 'https://www.npmjs.com/policies/personal-plan',
  '/policies/receiving-reports': 'https://www.npmjs.com/policies/receiving-reports',
  '/policies/trademark': 'https://www.npmjs.com/policies/trademark',
  '/policies/disputes': 'https://www.npmjs.com/policies/disputes',
  '/policies/npm-license': 'https://www.npmjs.com/policies/npm-license',
  '/policies/privacy': 'https://www.npmjs.com/policies/privacy',
  '/policies/recruiting-process': 'https://www.npmjs.com/policies/recruiting-process',
  '/policies/dmca': 'https://www.npmjs.com/policies/dmca',
  '/policies/open-source-terms': 'https://www.npmjs.com/policies/open-source-terms',
  '/policies/private-terms': 'https://www.npmjs.com/policies/private-terms',
  '/policies/security': 'https://www.npmjs.com/policies/security',

  '/enterprise/whitelist': 'https://npme.npmjs.com/docs/workflow/mirroring.html',
  '/enterprise/index': 'https://npme.npmjs.com',
  '/enterprise/intro': 'https://npme.npmjs.com',
  '/enterprise/requirements': 'https://npme.npmjs.com/docs/up-and-running/requirements.html',
  '/enterprise/installation': 'https://npme.npmjs.com/docs/up-and-running/',
  '/enterprise/client-configuration': 'https://npme.npmjs.com/docs/cli/',
  '/enterprise/using-it': 'https://npme.npmjs.com/docs/workflow/',
  '/enterprise/mirroring': 'https://npme.npmjs.com/docs/workflow/mirroring.html',
  '/enterprise/github': 'https://npme.npmjs.com/docs/up-and-running/auth/github.html',
  '/enterprise/updating': 'https://npme.npmjs.com/docs/troubleshooting/faq.html#how-do-i-upgrade-npm-enterprise',
  '/enterprise/server-configuration': 'https://npme.npmjs.com/docs/up-and-running/customization.html',
  '/enterprise/add-ons': 'https://npme.npmjs.com/docs/tutorials/addons.html',
  '/enterprise/custom-authentication': 'https://npme.npmjs.com/docs/up-and-running/auth/',
  '/enterprise/no-authentication': 'https://npme.npmjs.com/docs/up-and-running/auth/open.html',
  '/enterprise/pipelines': 'https://npme.npmjs.com/docs/tutorials/pipelines.html',
  '/enterprise/running-on-aws': 'https://npme.npmjs.com/docs/up-and-running/platforms/aws.html',

  '/misc/index': '/',
  '/package.json': '/files/package.json',
  '/getting-started/working-with-orgs': '/orgs/what-are-orgs'
}
